= Laserfiche Connector - Mule 4

== About Laserfiche Connector
Laserfiche software enables organizations to speed up operations and simplify complex tasks with a content services platform for document and records management and business process automation. Centralize and secure your organization’s data, while still offering teams the convenience to collaborate and find what they need fast.

The Laserfiche Connector performs common integration tasks for engaging with data within a Laserfiche repository. The connector leverages the Laserfiche API, allowing you to import and export data in and out of the Laserfiche repository. Send data from connected systems to Laserfiche and take advantage of search features to retrieve that data quickly.

== About Laserfiche
Laserfiche is the leading global provider of intelligent content management and business process automation. The Laserfiche® platform enables organizations in more than 80 countries to transform into digital businesses. Customers in every industry—including government, education, financial services and manufacturing—use Laserfiche® to boost productivity, scale their business and deliver digital-first customer experiences.